spring:
  datasource:

    url: jdbc:mysql://localhost:3306/vendor?useSSL=false
    username: root
    password: root




  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect



